summary: notes/id
put:
    requestBody:
        content:
            application/json:
                schema:
                    $ref: '#/components/schemas/noteResponse'
    parameters:
        - name: id
          schema:
              format: int32
              type: integer
          in: path
          required: true
    responses:
        '200':
            content:
                application/json: { }
            description: Response ok.
    summary: No content
delete:
    tags:
        - Notes
    parameters:
        - name: id
          description: Note ID
          in: path
          required: true
    responses:
        '204':
            description: Note deleted
        '401':
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/error'
                    examples:
                        Unauthorized:
                            value:
                                message: Unauthorized
            description: Unauthorized
    security:
        - Bearer: [ ]
    summary: Delete a note
patch:
    parameters:
        - name: id
          schema:
              format: int32
              type: integer
          in: path
          required: true
    responses:
        '204':
            content:
                application/json: { }
            description: No content
    security:
        - Bearer: [ ]
    summary: No content
